
ACTION Act_Main_P1025:
		
	//Machine Setting - AIV Communication
	//Parameter
//	tyP1025McSetAIVComm.tyAIVComm.tyNumSvrPort.diValue		:= UINT_TO_DINT(p_tyMcParamCurr.tyAIVComm.uiSvrPort);
//	tyP1025McSetAIVComm.tyAIVComm.tyNumAllwClntPort.diValue	:= UINT_TO_DINT(p_tyMcParamCurr.tyAIVComm.uiClientPort);
//	tyP1025McSetAIVComm.tyAIVComm.tyStringAllwClntIP.sValue	:= p_tyMcParamCurr.tyAIVComm.sClientAddress;
	
END_ACTION
