(** 2021-08-20 **)
ACTION Act_Main_P1028:
	
	
	//Parameter
	tyP1028McSetRS232Setting.tyRS232Set.tyNumStartCode1.diValue	:= p_tyMcParamCurr.diRS232StartCode1;
	tyP1028McSetRS232Setting.tyRS232Set.tyNumStartCode2.diValue	:= p_tyMcParamCurr.diRS232StartCode2;
	tyP1028McSetRS232Setting.tyRS232Set.tyNumEndCode1.diValue	:= p_tyMcParamCurr.diRS232EndCode1;
	tyP1028McSetRS232Setting.tyRS232Set.tyNumEndCode2.diValue	:= p_tyMcParamCurr.diRS232EndCode2;
	
	
END_ACTION
